# Creating a NumPy array

Create a NumPy array is to create one from a list by passing it to the np.array() function

In [1]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
arr = np.array(list1)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4]


The key difference between an array and a list is that arrays are designed to handle vectorised operations while a python lists are not.
That means, if you apply a function, it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do this is something like this:

In [2]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
list1 = list1 + 2

TypeError: can only concatenate list (not "int") to list

That was not possible with a list, but you can do that on an array:

In [ ]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
arr = np.array(list1)
arr = arr + 2

print (arr)


[2 3 4 5 6]


# Create a 2d array from a list of list

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# The dtype argument

- You can specify the data-type by setting the dtype() argument.
- Some of the most commonly used NumPy dtypes are: float, int, bool, str, and object.

In [ ]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print(arr3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


You can also convert it to a different data-type using the astype method.

In [ ]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')

arr3_str = arr3.astype('int').astype('str')
print(arr3_str)

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


However, if you are uncertain about what data type your array will hold, or if you want to hold characters and numbers in the same array, you can set the dtype as 'object'.

In [ ]:
arr_obj = np.array([1, 'a'], dtype='object')
print(arr_obj)

[1 'a']


You can always convert an array into a list using the tolist() command.

In [ ]:
arr_list = arr3.tolist()

print(type(arr3))
print (type(arr_list))
print(arr_list)

<class 'numpy.ndarray'>
<class 'list'>
[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]


Note: Remember that, unlike lists, all items in an array have to be of the same type.

# Inspecting a NumPy array

There are a range of functions built into NumPy that allow you to inspect different aspects of an array:

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print("shape :", arr3.shape)
print("Data type :", arr3.dtype)
print("Size :", arr3.size)
print("Num dimensions :", arr3.ndim)

shape : (3, 3)
Data type : float64
Size : 9
Num dimensions : 2


# Extract specific items from array

You can extract portions of the array using indices, much like when you’re working with lists.
Unlike lists, however, arrays can optionally accept as many parameters in the square brackets as there are number of dimensions

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print("whole:", arr3)
print("Part:", arr3[ 0:2 , 1:2 ])

whole: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Part: [[1.]
 [4.]]


A boolean index array is of the same shape as the array-to-be-filtered, but it only contains TRUE and FALSE values.

In [ ]:
boo = arr3 > 2
print(boo)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


np.where(condition, x, y) will return an array with elements set to x where condition is True, and set to y where condition is False.

In [ ]:
binary = np.where (arr3, 1, 0)
print (binary)

[[0 1 1]
 [1 1 1]
 [1 1 1]]
