# Creating a NumPy array

Create a NumPy array is to create one from a list by passing it to the np.array() function

In [3]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
arr = np.array(list1)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[0 1 2 3 4]


The key difference between an array and a list is that arrays are designed to handle vectorised operations while a python lists are not.
That means, if you apply a function, it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do this is something like this:

In [4]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
list1 = list1 + 2

TypeError: can only concatenate list (not "int") to list

That was not possible with a list, but you can do that on an array:

In [ ]:
import numpy as np

list1 = [0, 1, 2, 3, 4]
arr = np.array(list1)
arr = arr + 2

print (arr)


[2 3 4 5 6]


# Create a 2d array from a list of list

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr2 = np.array(list2)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# The dtype argument

- You can specify the data-type by setting the dtype() argument.
- Some of the most commonly used NumPy dtypes are: float, int, bool, str, and object.

In [ ]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print(arr3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


You can also convert it to a different data-type using the astype method.

In [ ]:
list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')

arr3_str = arr3.astype('int').astype('str')
print(arr3_str)

[['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']]


However, if you are uncertain about what data type your array will hold, or if you want to hold characters and numbers in the same array, you can set the dtype as 'object'.

In [ ]:
arr_obj = np.array([1, 'a'], dtype='object')
print(arr_obj)

[1 'a']


You can always convert an array into a list using the tolist() command.

In [ ]:
arr_list = arr3.tolist()

print(type(arr3))
print (type(arr_list))
print(arr_list)

<class 'numpy.ndarray'>
<class 'list'>
[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]


Note: Remember that, unlike lists, all items in an array have to be of the same type.

# Inspecting a NumPy array

There are a range of functions built into NumPy that allow you to inspect different aspects of an array:

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print("shape :", arr3.shape)
print("Data type :", arr3.dtype)
print("Size :", arr3.size)
print("Num dimensions :", arr3.ndim)

shape : (3, 3)
Data type : float64
Size : 9
Num dimensions : 2


# Extract specific items from array

You can extract portions of the array using indices, much like when you’re working with lists.
Unlike lists, however, arrays can optionally accept as many parameters in the square brackets as there are number of dimensions

In [ ]:
import numpy as np

list2 = [[0,1,2],[3,4,5],[6,7,8]]
arr3 = np.array(list2, dtype='float')
print("whole:", arr3)
print("Part:", arr3[ 0:2 , 1:2 ])

whole: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
Part: [[1.]
 [4.]]


A boolean index array is of the same shape as the array-to-be-filtered, but it only contains TRUE and FALSE values.

In [ ]:
boo = arr3 > 2
print(boo)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


np.where(condition, x, y) will return an array with elements set to x where condition is True, and set to y where condition is False.

In [ ]:
binary = np.where (arr3, 1, 0)
print (binary)

[[0 1 1]
 [1 1 1]
 [1 1 1]]


# NumPy Questions

1. What is the primary purpose of NumPy in Python?

A) Web development
B) Data manipulation
C) Numerical computing
D) Text processing
Answer: C

2. How do you import NumPy in a Python script?

A) import np
B) import numpy as np
C) import numpy
D) import np as numpy
Answer: B

3. Which function creates a NumPy array filled with zeros?

A) np.zeros()
B) np.ones()
C) np.empty()
D) np.full()
Answer: A

4. What does np.arange(10) do?

A) Creates an array from 1 to 10
B) Creates an array from 0 to 10
C) Creates an array from 0 to 9
D) Creates an array of 10 ones
Answer: C

5. How do you get the shape of a NumPy array arr?

A) arr.shape()
B) np.shape(arr)
C) arr.shape
D) shape(arr)
Answer: C

6. What is the output of np.array([1, 2, 3]) + np.array([4, 5, 6])?

A) [5, 7, 9]
B) [14, 25, 36]
C) [4, 5, 6, 1, 2, 3]
D) Error
Answer: A

7. Which function reshapes a NumPy array?

A) np.reshape()
B) np.resize()
C) np.format()
D) np.shape()
Answer: A

8. What does np.linspace(0, 1, 5) do?

A) Creates an array of 5 zeros
B) Creates an array from 0 to 1 with 5 equally spaced values
C) Creates an array from 0 to 4
D) Creates an array from 0 to 1 with 5 random values
Answer: B

9. How do you perform element-wise multiplication of two arrays a and b?

A) a * b
B) np.multiply(a, b)
C) a.dot(b)
D) Both A and B
Answer: D

10. What does np.mean(arr) compute?

A) The sum of all elements in arr
B) The average of all elements in arr
C) The median of all elements in arr
D) The mode of all elements in arr
Answer: B

11. Which function is used to find the maximum value in a NumPy array arr?

A) np.max(arr)
B) np.maximum(arr)
C) np.argmax(arr)
D) np.amax(arr)
Answer: A

12. How do you create a 2x3 array filled with ones?

A) np.ones((2, 3))
B) np.full((2, 3), 1)
C) np.array([1, 1, 1, 1, 1, 1]).reshape((2, 3))
D) All of the above
Answer: D

13. What does arr.T do to the array arr?

A) Transposes the array
B) Flattens the array
C) Sorts the array
D) Reverses the array
Answer: A

14. How do you find the indices of non-zero elements in an array arr?

A) np.nonzero(arr)
B) arr.nonzero()
C) np.where(arr != 0)
D) All of the above
Answer: D

15. What does np.concatenate([a, b]) do if a and b are arrays?

A) Adds the elements of b to a
B) Combines a and b into a single array
C) Multiplies the elements of a with b
D) Finds the common elements of a and b
Answer: B

16. Which function is used to create an identity matrix?

A) np.eye()
B) np.identity()
C) np.ones()
D) np.identity_matrix()
Answer: A

17. What does np.dot(a, b) compute if a and b are arrays?

A) Element-wise multiplication
B) Matrix product
C) Cross product
D) Addition
Answer: B

18. How do you save a NumPy array arr to a file?

A) np.save('filename', arr)
B) np.save_array('filename', arr)
C) np.write('filename', arr)
D) np.export('filename', arr)
Answer: A

19. What is the output of np.sqrt(np.array([1, 4, 9]))?

A) [1, 2, 3]
B) [1, 16, 81]
C) [1, 4, 9]
D) Error
Answer: A

20. How do you stack two arrays a and b vertically?

A) np.vstack((a, b))
B) np.hstack((a, b))
C) np.column_stack((a, b))
D) np.concatenate((a, b), axis=1)
Answer: A